version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brain-agriculture-frontend
    restart: always
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://147.79.83.158:3006
    networks:
      - laudorrt_laudorrt-network

  backend:
    build:
      context: ./backend-nest
      dockerfile: Dockerfile
    container_name: brain-agriculture-backend
    restart: always
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - DB_HOST=laudorrt-postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=Be111290@#
      - DB_DATABASE=brain_agriculture
    networks:
      - laudorrt_laudorrt-network

networks:
  laudorrt_laudorrt-network:
    external: true