version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brain-agriculture-frontend
    restart: always
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://147.79.83.158:3006
    networks:
      - brain-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brain-agriculture-backend
    restart: always
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=Be111290@#
      - DB_DATABASE=brain_agriculture
    depends_on:
      - postgres
    networks:
      - brain-network

  postgres:
    image: postgres:14-alpine
    container_name: brain-agriculture-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Be111290@#
      POSTGRES_DB: brain_agriculture
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - brain-network

networks:
  brain-network:
    driver: bridge

volumes:
  postgres_data: